### ISSUE TITLE
[2.0.0 BETA4] Lightning Dragon Roosts not spawning, Caves work just fine.

### ISSUE THREAD

**Issue by Carro1001** [Alex-the-666/IceAndFireBeta#142]
Not a single one spawns, even on a world entirely made of savanna

**Comment by kodabeer** [comment]
![2020-09-04_23 35 18](https://user-images.githubusercontent.com/53926065/92296876-623a0300-ef07-11ea-9796-67df7a2f0579.png)
doubt
