### ISSUE TITLE
[2.0.0 Beta2] Game crashes when throwing a death worm egg

### ISSUE THREAD

**Issue by Pokerfrog** [Alex-the-666/IceAndFireBeta#65]
[crash-2020-09-02_09.34.47-client.txt](https://github.com/Alex-the-666/IceAndFireBeta/files/5162609/crash-2020-09-02_09.34.47-client.txt)
[crash-2020-09-02_09.36.40-client.txt](https://github.com/Alex-the-666/IceAndFireBeta/files/5162611/crash-2020-09-02_09.36.40-client.txt)
First one is regular death worm egg
Second is giant death worm egg

**Comment by AlexModGuy** [comment]
fixed
