### ISSUE TITLE
[2.0.0 BETA3] Dragon Caves/Nests can be griefed by terrain gen, like lakes and caves

### ISSUE THREAD

**Issue by Carro1001** [Alex-the-666/IceAndFireBeta#93]
![image](https://user-images.githubusercontent.com/47877096/92050036-6842af00-ed62-11ea-9e0a-f1b93995b2dc.png)
Don't know if this is intended or not, but doesn't look like it

**Comment by AlexModGuy** [comment]
looks more natural like this imo
